#!usr/bin/env python3
import re

# create a function to format string of DNA, each line no more than 60 nt

dna = '''CTTCAAACGTGTCTATCTATTTATTCTAATAAATTTCTATAATAGACACTTTAACTTATTTTTACTTATTTATTAATGAG
TATTCGAGAAGACAGGAATCAGGATGCAACTATATATCTTGGCAATCTTGATGAAAAAGTAACGGATTCTATTTTGTTTG
AGTTATGCCTGCAGGCAGGTCCAGTTGTAAATATTCATATTCCAAGAGATAGAGTAAGGAATAGTCATAATGGCTTTGGT
TTCTGCGAATTCTTACACGAACAAGATGTTGAGTATGCATGTCAAATTCTGAATCAAGTAAAGTTGTTTGGAAAGCCTAT
AAGGGTCAATAGAGCTAGCCAGGACAGAGGAGTCAATACCTTAATTGGTGCAAATTTATTTGTTGGCAACTTGGATCCTC
TTGTTGATGAACGCGTATTGTACGATACATTTTCTGCTTTGGGACAACTTGTCAAGGCACCTCAGGTAGCAAGAGACGAG
AATGGAAGGTCGAAAGGTTATGGTTTTGTTAGCTACGATTCTTTTGAAACCGCTGATGCAGCCATTGAGGCCATGAATAA
TCAGTTTTTAATGAATAAACCAATTACCGTGTCATACGCCTTTAAACGCGAAGGAAAGGGTGAACGTCACGGAGATATTG
CGGAAAGAAAGCTAGCAGCAGCCGCTAAAAAGAATAAAGTTGCCGTTACTCCTCAGAGTACTCTGCCTCCAGGATTTTCA
CCCGCCACTCCTGCTCCAACATCTGCTGCTAATACTCCAGCAACAATTGCTGCTACATCGATACCTCCTGTACCGAATGT
TCCTCTAGTGGGAGCAACTACTGCCGTCCCTCCCTTGTCAATACCTAATGTTCTTCCTTTCACTGCTGCACAGCATTTCC
CTGGAATGCCTGCTATGCCAATGATGAATGTTCCAATGGGCCCTGGAGGTGCACCACTTGTCCCCCCTCCACCACCAGGA
ATGGTGATGGCTTCTCCTTCTCCTGCTGCTGCTACCATACCTGGTGCTCCTGTAATGCCAAACATACCATTTTATCAAAC
AATCAATGCACAAAATGGATACAGTCAACAACAAAGGAGGTAAAATATTTTAAAAAGAAGCAAAATAACTACCATTGTTGCTCAAACGCCGG'''
width = 80

def format_DNA(dna, wid):
    dna2 = ''
    for nt in re.findall(r'\w', dna):
        dna2 = dna2 + nt
    for i in range(0, len(dna2), wid+1):
        dna2 = dna2[:i] + '\n' + dna2[i:]
    i += (wid+1)
    if i % wid+1:
        final_cut = i - (i%(wid+1))
        dna2 = dna2[:final_cut] + '\n' + dna2[final_cut:]
    return dna2

print(format_DNA(dna, width))